FROM node:20-alpine
RUN apk add --no-cache git

RUN npm install -g @asyncapi/cli @asyncapi/generator @asyncapi/go-watermill-template

RUN git config --global --add safe.directory /app

WORKDIR /app

ENTRYPOINT [ "sh", "-c" ]